CREATE TABLE players_stats (
 id serial PRIMARY KEY,
 game_id integer REFERENCES games_info(game_id),
 team_id integer REFERENCES teams_info(id),
 player_id integer REFERENCES players_info(id),
 pass_eff decimal,
 attacking_passes_accurate integer,
 passes_forward_perc decimal,
 air_challenges_eff decimal,
 def_challenges_eff decimal,
 ball_recoveries integer,
 ball_recovery_in_opp_half integer,
 defensive_challenges_successful integer,
 dribbles integer,
 fouls_commited integer,
 foul_suffered integer,
 goals integer,
 interceptions integer,
 interceptions_in_opp_half integer,
 lost_balls integer,
 passes_into_final_third integer,
 passes_into_opp_box integer,
 minutes_played integer,
 passes integer,
 short_passes integer,
 medium_passes integer,
 long_passes integer,
 shots integer,
 red_cards integer,
 yellow_cards integer,
 tackles integer,
 in_first_11 integer,
 sub_in integer,
 sub_out integer,
 other_stats jsonb NOT NULL
 );
