CREATE TABLE teams_stats (
 id serial PRIMARY KEY,
 game_id integer REFERENCES games_info(game_id),
 team_id integer REFERENCES teams_info(id),
 goals integer,
 penalty_goals integer,
 goals_conceded integer,
 passes_forward_perc decimal,
 shots_from_counter_attacks_perc decimal,
 shots_from_positional_attacks_perc decimal,
 shots_from_set_pieces_attacks_perc decimal,
 ball_possession decimal NOT NULL,
 ball_recoveries_in_10_sec integer,
 ball_recoveries_in_10_sec_in_opp_half integer,
 turnovers_in_own_half integer,
 turnovers_in_opp_half integer,
 team_pressing_successful_perc decimal,
 attacking_mentality_index decimal,
 average_length_of_passes decimal,
 actions_in_opp_third integer,
 average_distance_to_the_goal_at_ball_recoveries decimal,
 ball_possession_15_45_sec_number integer,
 ball_possession_5_15_sec_number integer,
 ball_possession_0_5_sec_number integer,
 ball_possession_45_more_sec_number integer,
 possession_time_in_the_final_third integer,
 opp_possession_sec integer,
 own_possession_sec integer,
 shots integer,
 team_pressing decimal,
 passes_in_the_opposition_half integer,
 other_stats jsonb NOT NULL
 );
